(function(){
  const skinJp = `肌は明るく均一で透明感のある色白のトーンを維持してください。ページを進めるごとに日焼けが強くなったり、肌が徐々に暗くなったりしないようにしてください。自然光による陰影は残しつつ、強いブロンズ化、過度な日焼け、オレンジ寄りの色調変化を避け、元画像の明るい肌色を一貫して保ってください。`;
  const skinEn = `Maintain a bright, even, luminous fair skin tone consistent with the reference. Do not let the skin become progressively more tanned, darker, heavily bronzed, or orange-toned across pages. Preserve natural light and shadow while keeping the reference skin tone consistent.`;

  const hypertrophy = {
    id:'hypertrophy',
    title:'💪 MUSCLE HYPERTROPHY',
    text:`【BODY：MUSCLE HYPERTROPHY】\n\n元画像の顔立ち、骨格、身長感、自然な肌質を維持しながら、全身の筋肉量を明確に増やしてください。\n\n肩、上腕、前腕、胸部、広背筋、腹部、臀部、大腿四頭筋、内転筋、ハムストリングス、ふくらはぎなどをバランスよく筋肥大させ、全身としてより厚みと立体感のある女性アスリート体型にしてください。\n\n元画像に見られる腹部・大腿部のvascularity、筋肉のセパレーション、ストリエーションは維持または自然に強調してください。単一部位だけを極端に巨大化させたり、骨格や関節の比率を崩したりせず、現実的な人体構造を保ってください。\n\nそれ以外の人物の特徴、写真表現、ロケーション、ポーズ、衣装、誌面構成についてはMASTERおよび各差分の指示を維持してください。`,
    textEn:`[BODY: MUSCLE HYPERTROPHY]\n\nKeep the same face, skeletal proportions, apparent height, and natural skin texture as the reference while clearly increasing overall muscular mass.\n\nDevelop the shoulders, upper arms, forearms, chest, lats, abdomen, glutes, quadriceps, adductors, hamstrings, and calves in balanced proportion, creating a thicker, more three-dimensional female athlete physique.\n\nPreserve or naturally enhance the reference abdominal and thigh vascularity, muscle separation, and subtle striations. Do not enlarge a single body part disproportionately or distort joints and skeletal proportions. Keep the anatomy realistic.\n\nMaintain all other MASTER, SCENE, POSE, OUTFIT, and LAYOUT instructions.`
  };

  const en = {
    masters:{
      attack:`This image is a two-page spread from a high-end photobook featuring an adult professional female fitness model.\n\nCreate the next spread while preserving the same woman: facial features, hairstyle, distinctive muscular physique, natural skin texture, and overall photographic continuity.\n\nUse exactly the number of compositions specified by the LAYOUT block. If no LAYOUT block is present, choose a natural editorial count. Give each composition a clearly different location treatment, pose, expression, camera angle, focal length, light direction, and background atmosphere while keeping the spread visually coherent as one shooting session.\n\nPreserve the reference level of muscularity, abdominal and thigh vascularity, muscle separation, and overall conditioning. Do not reduce or hide these traits. They may be rendered at the same level or slightly stronger when appropriate, while keeping anatomy and skin realistic.\n\nMix close-up, medium close-up, upper-body, full-body, low-position, and in-between-motion compositions as appropriate. Include natural transitions such as turning, twisting, sitting down, rising, or changing posture rather than relying only on finished poses.\n\nUse close photographer-to-model distance, direct and averted gaze, low camera positions, oblique viewpoints, over-the-shoulder perspectives, shallow depth of field, and foreground layering to create an immersive editorial presence.\n\nAim for a sophisticated, person-centered high-end editorial photobook rather than a conventional sports advertisement. Make the model's presence, gaze, gestures, silhouette, and interplay of light and shadow the visual focus.\n\nUse natural daylight, window light, and soft side light. Preserve realistic skin texture and avoid artificial shine, extreme HDR, and excessive sharpening.\n\nIf an OUTFIT block is present, prioritize it. Otherwise choose clothing that naturally fits the setting and activity.\n\nKeep typography minimal and use the full spread with varied image sizes, spacing, and placement while maintaining a cohesive premium layout.\n\n${skinEn}`,
      neutral:`This image is a two-page spread from a high-end photobook featuring an adult professional female fitness model.\n\nCreate the next spread as the same woman, preserving her face, hairstyle, distinctive muscular build, natural skin texture, and photographic continuity.\n\nUse exactly the number of compositions specified by the LAYOUT block. If no LAYOUT block is present, choose a natural editorial count. Vary location, pose, expression, camera angle, framing, light direction, and background atmosphere while keeping all images coherent as part of one session.\n\nMaintain the reference muscular mass, natural abdominal and thigh vascularity, muscle separation, and realistic anatomy. Do not weaken or obscure these physical traits.\n\nCombine close-ups, medium close-ups, upper-body portraits, full-body views, and motion-based compositions. Include both detailed views of the face and musculature and wider frames that clearly show overall balance and posing.\n\nUse low angles, oblique viewpoints, depth, and moments immediately before or after movement to create an immersive editorial rhythm. Avoid awkward cropping, extreme wide-angle distortion, malformed faces, hands, or limbs.\n\nUse refined high-end female-athlete editorial photography with natural light and realistic skin texture. Avoid artificial gloss, extreme HDR, and excessive sharpening.\n\nKeep text minimal and create a premium spread with varied image sizes, margins, and placement.\n\n${skinEn}`,
      safe:`This image is a two-page spread from a high-end female-athlete photobook featuring an adult professional female fitness model.\n\nCreate the next spread as the same woman, preserving her face, hairstyle, muscular physique, natural skin texture, and visual continuity.\n\nUse exactly the number of compositions specified by the LAYOUT block. If no LAYOUT block is present, choose a natural editorial count. Vary pose, expression, camera angle, framing, light direction, and background while keeping the spread coherent as a sports and fitness session.\n\nMaintain the reference muscular mass, abdominal and thigh vascularity, muscle separation, realistic anatomy, and balanced overall proportions.\n\nFavor natural athletic actions such as standing, walking, stretching, warming up, training, focusing on competition, and resting after activity. Combine portraits, upper-body, full-body, and movement frames.\n\nUse straightforward, three-quarter, side, telephoto, and action-following perspectives. Avoid extreme wide-angle distortion and unnatural emphasis on isolated body parts.\n\nUse refined female-athlete editorial photography with natural daylight, window light, and soft side light. Preserve realistic skin texture and avoid artificial shine, extreme HDR, and excessive sharpening.\n\nKeep text minimal and use a cohesive premium sports-editorial layout.\n\n${skinEn}`
    },
    layouts:{
      '1':`[LAYOUT: 1 SHOT]\n\nBuild the entire spread around one primary composition. Make the model large and visually dominant, with enough information in a single image to communicate the location, expression, pose, and lighting. Prioritize this one-shot instruction over any composition-count wording in MASTER.`,
      '2':`[LAYOUT: 2 SHOTS]\n\nUse exactly two distinct compositions: one dominant main image and one supporting image. Clearly vary camera distance, expression, body direction, and framing. Prioritize this two-shot instruction over any composition-count wording in MASTER.`,
      '3':`[LAYOUT: 3 SHOTS]\n\nUse exactly three distinct compositions. Vary pose, expression, camera distance, framing, and body direction. Use one large main image and two supporting images rather than equal-size panels. Prioritize this three-shot instruction over any composition-count wording in MASTER.`,
      '4':`[LAYOUT: 4 SHOTS]\n\nUse exactly four distinct compositions with clear variation in pose, expression, camera distance, body direction, and framing. Mix close, medium, and full-body images and vary panel sizes to create an editorial rhythm. Prioritize this four-shot instruction over any composition-count wording in MASTER.`,
      '5':`[LAYOUT: 5 SHOTS]\n\nUse exactly five distinct compositions. Combine one or two larger anchor images with several smaller supporting frames. Vary pose, expression, camera angle, distance, and movement while keeping each image large enough to remain readable. Prioritize this five-shot instruction over any composition-count wording in MASTER.`
    },
    scenes:{
      beach:`[SCENE: BEACH]\n\nShoot on a bright, open coastline using broad sand, the waterline, blue sea, and rocks as varied backgrounds. Change shooting positions enough to create strong background variety within the same coast.\n\nUse sea breeze, natural movement in hair and clothing, walking on sand, and brief pauses near the waterline to create genuine outdoor motion.\n\nMaintain all other MASTER instructions.`,
      hotel:`[SCENE: SOFT INTERIOR / NATURAL LIGHT]\n\nUse a quiet, refined interior with large windows, white curtains, soft bedding, white sheets, cushions, and wood furniture.\n\nHave the model sit on the soft bedding, sit with knees raised, rest on her side, recline naturally on her back, support her upper body on an elbow or forearm, or be captured while rising. Keep the gestures believable as relaxed indoor portraiture.\n\nUse soft window light as the main source, including diffused light through curtains and bounce from white fabric to shape the face, shoulders, abdomen, and thighs gently.\n\nCreate a calm, close-distance editorial atmosphere with natural morning-to-afternoon daylight, realistic shadow, and natural skin texture. Avoid theatrical studio lighting.\n\nMaintain all other MASTER, POSE, and OUTFIT instructions.`,
      pool:`[SCENE: POOL]\n\nUse an open outdoor pool and surrounding deck. Vary backgrounds using the water surface, deck, lounge furniture, architecture, and surrounding scenery.\n\nUse reflected light from the water, natural breeze, and a bright summer atmosphere while changing shooting direction across compositions.\n\nMaintain all other MASTER instructions.`,
      'city-night':`[SCENE: CITY NIGHT]\n\nUse an urban night environment with building lights, sidewalks, glass walls, rooftops, and reflected neon. Mix environmental light with practical artificial light for a sharper, cinematic atmosphere.\n\nInclude natural actions such as walking, stopping, and turning. Maintain all other MASTER instructions.`,
      gym:`[SCENE: GYM]\n\nUse a real training facility with free weights, machines, benches, racks, mirrors, and aisles as varied backgrounds.\n\nCapture training, rest between sets, warm-up, equipment preparation, and movement through the space. Maintain all other MASTER instructions.`,
      'daily-interior':`[SCENE: DAILY INTERIOR]\n\nUse a bright, calm residential or modern interior with windows, sofa, table, hallway, and kitchen areas.\n\nInclude ordinary gestures such as walking, holding a drink, looking outside, or sitting to rest. Maintain all other MASTER instructions.`,
      nature:`[SCENE: NATURE]\n\nUse a green park, forest, lakeside, grassland, or walking trail. Incorporate dappled light, breeze, foreground plants, and layered depth.\n\nInclude walking, pausing, and looking around naturally. Maintain all other MASTER instructions.`,
      'sports-hall':`[SCENE: SPORTS HALL]\n\nUse a bright indoor sports facility with court lines, nets, benches, walls, and spectator seating.\n\nInclude warm-up, footwork, athletic movement, rest, and transitions around the facility. Maintain all other MASTER instructions.`,
      sunset:`[SCENE: SUNSET]\n\nShoot outdoors from late afternoon into magic hour, using a coast, rooftop, park, or city environment where low sunlight is visually effective.\n\nUse backlight, side light, long shadows, and a soft sky, mixing quiet standing, walking, and turning moments for a cinematic mood. Maintain all other MASTER instructions.`,
      tennis:`[SCENE: TENNIS]\n\nUse a bright outdoor tennis court with hard court surfaces, net, baseline, bench, fence, spectator seating, and nearby club architecture as varied backgrounds.\n\nInclude serve preparation, moments immediately before or after forehand and backhand strokes, chasing the ball, walking with a racket, resting on the bench, and resetting between points. Mix athletic action with quieter courtside portraits.\n\nMaintain all other MASTER instructions.`,
      washitsu:`[SCENE: WASHITSU / SHOJI LIGHT]\n\nUse a quiet traditional Japanese tatami room with shoji screens, wooden posts, low furniture, and a tokonoma alcove.\n\nUse soft daylight diffused through white shoji as the main light source, gently shaping the face, shoulders, abdomen, and thighs. Add narrow shafts of light through openings, soft shadows on tatami, and subtle interior contrast for a warm, tranquil atmosphere.\n\nKeep the lighting believable as real morning-to-afternoon daylight rather than studio light. Maintain all other MASTER, POSE, and OUTFIT instructions.`
    },
    poses:{
      standing:`[POSE: STANDING]\n\nBuild around standing poses: front, three-quarter, side, slight torso twist, leaning naturally against a wall or rail, beginning to walk, or stopping mid-step. Vary arm position, gaze, weight distribution, and small gestures. Include natural in-between moments rather than only finished poses. Maintain all other MASTER and SCENE instructions.`,
      sitting:`[POSE: SITTING / RELAXED]\n\nUse seated and relaxed postures on chairs, benches, sofas, floors, or steps appropriate to the location. Vary bent knees, one leg extended, torso twist, leaning back, leaning forward, resting, and the moment before standing. Mix direct gaze, averted gaze, touching hair, and relaxed expressions. Maintain all other MASTER and SCENE instructions.`,
      motion:`[POSE: MOTION]\n\nCenter the spread on movement rather than static posing: walking, turning, changing direction, light running, arm motion, and natural movement of hair and clothing. Mix moments immediately before, during, and after movement. Preserve facial and anatomical clarity while keeping a sense of motion. Maintain all other MASTER and SCENE instructions.`,
      'candid-close':`[POSE: CANDID / CLOSE]\n\nCreate an intimate-feeling photographer-to-model distance using close portraiture, direct or averted gaze, turning, touching hair, light torso twists, leaning against walls or furniture, sitting, knees raised, looking up from a forward lean, and transitions between postures. Mix standing, seated, low, and relaxed positions, alternating camera-aware portraits with candid in-between moments. Maintain all other MASTER and SCENE instructions.`,
      'low-close':`[POSE: LOW & CLOSE]\n\nWhen LAYOUT specifies multiple compositions, use low ground-level postures in roughly half of them. Include deep squats, one knee down, hands touching the floor or sand, hands-and-knees support, sitting on the floor, lying on the side or back, supporting the upper body on elbows or forearms, and moments while rising.\n\nUse floor-level camera positions, model-height viewpoints, diagonal front and rear angles, close portraits, shallow depth of field, and bold editorial crops. Avoid letting the spread default to standing full-body poses. Maintain all other MASTER and SCENE instructions.`,
      'low-athletic':`[POSE: LOW POSTURES / ATHLETIC]\n\nUse low postures that naturally fit athletic activity: one knee down, deep squat, hands-and-knees stretching, lying on a mat to recover, side-lying stretches, elbow-supported rest, sitting on the floor after activity, and rising. Make the athletic reason for the posture visually clear through warm-up, stretching, cool-down, or recovery context. Maintain realistic full-body balance and all other MASTER and SCENE instructions.`
    },
    outfits:{
      bold:`[OUTFIT: BOLD MINIMAL EDITORIAL]\n\nChoose lightweight, minimal, high-end editorial styling appropriate to the location.\n\nAt a coast, pool, or resort setting, prioritize refined swimwear with compact two-piece silhouettes, slim straps, open necklines, higher leg lines, lower-rise bottoms, side ties, and asymmetric cuts that naturally reveal the trained silhouette.\n\nIndoors, use slim straps, close-fitting silhouettes, lightweight materials, delicate details, and compact coordinated pieces that work with soft natural light.\n\nAvoid repeatedly defaulting to training sports bras, heavy competition tops, or high-waisted sports shorts. Vary color, material, straps, cut, and silhouette across compositions. Maintain all other MASTER, SCENE, and POSE instructions.`,
      refined:`[OUTFIT: REFINED EDITORIAL]\n\nChoose polished high-end editorial styling that sits between bold minimal fashion and unrestricted random styling. Use fitted but not ultra-compact tops, clean two-piece looks, minimal one-piece designs, lightweight coordinated sets, and body-following silhouettes.\n\nAt a coast, pool, or resort, favor refined swimwear and resort styling. Indoors, favor minimal, elegant pieces that work with soft natural light. Avoid both extreme cuts and repetitive training-wear silhouettes. Maintain all other MASTER, SCENE, and POSE instructions.`,
      random:`[OUTFIT: RANDOM EDITORIAL]\n\nDo not fix clothing type, color, or design. Choose freely from sports fashion, modern casualwear, resort styling, minimal fashion, and fitted editorial clothing according to location, season, and shooting concept. Keep each page visually fresh. Maintain all other MASTER, SCENE, and POSE instructions.`,
      athletic:`[OUTFIT: ATHLETIC]\n\nChoose functional, polished clothing that naturally fits sports or training photography. Select sportswear, training wear, competition wear, or activewear appropriate to the location and activity, balancing genuine functionality with editorial fashion. Maintain all other MASTER, SCENE, and POSE instructions.`
    },
    bodies:{
      'full-bust':`[BODY: FULL BUST]\n\nKeep the same face, skeletal frame, muscular mass, abdominal and thigh vascularity, and overall body proportions as the reference while depicting a naturally large bust.\n\nKeep the chest anatomically integrated with the ribcage, shoulders, lats, and waist rather than appearing detached or artificially inflated. Maintain realistic anatomy and all other MASTER instructions.`,
      hypertrophy:hypertrophy.textEn
    }
  };

  function addSkin(text){
    if(!text) return text;
    if(text.includes('明るく均一で透明感のある色白')) return text;
    return `${text}\n\n${skinJp}`;
  }
  function setEnglish(data){
    if(!data) return;
    (data.masters||[]).forEach(x=>{if(en.masters[x.id]) x.textEn=en.masters[x.id]});
    (data.layouts||[]).forEach(x=>{if(en.layouts[x.id]) x.textEn=en.layouts[x.id]});
    (data.scenes||[]).forEach(x=>{if(en.scenes[x.id]) x.textEn=en.scenes[x.id]});
    (data.poses||[]).forEach(x=>{if(en.poses[x.id]) x.textEn=en.poses[x.id]});
    (data.outfits||[]).forEach(x=>{if(en.outfits[x.id]) x.textEn=en.outfits[x.id]});
    (data.bodies||[]).forEach(x=>{if(en.bodies[x.id]) x.textEn=en.bodies[x.id]});
  }
  function patch(data){
    if(!data) return;
    if(!data.selectedLanguage) data.selectedLanguage='jp';
    (data.masters||[]).forEach(x=>{x.text=addSkin(x.text)});
    if(!Array.isArray(data.bodies)) data.bodies=[];
    let h=data.bodies.find(x=>x.id==='hypertrophy');
    if(h){h.title=hypertrophy.title;h.text=hypertrophy.text;h.textEn=hypertrophy.textEn}
    else data.bodies.push(JSON.parse(JSON.stringify(hypertrophy)));
    setEnglish(data);
  }

  patch(window.initialData);
  try{
    const key='promptPaletteV2';
    const raw=localStorage.getItem(key);
    if(raw){const saved=JSON.parse(raw);patch(saved);localStorage.setItem(key,JSON.stringify(saved));}
  }catch(e){}
})();